## TensorFlow 1.X




### Instalando o TensorFlow 1.X



In [1]:
!pip uninstall -y tensorflow #Comando necessário, pois o TensorFlow-gpu não desinstala a versão mais recente do Tensorflow, pode gerar conflitos.

Uninstalling tensorflow-2.2.0:
  Successfully uninstalled tensorflow-2.2.0


In [2]:
!pip install tensorflow-gpu==1.15

     |████████████████████████████████| 411.5MB 37kB/s 
     |████████████████████████████████| 3.8MB 33.4MB/s 
     |████████████████████████████████| 512kB 37.1MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=5c2ef5515fb39737588ad373b892becf12a16b49856f1495b81609b165674469
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.10.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0


In [21]:
import tensorflow as tf

In [22]:
tf.__version__

'1.15.0'

### Constantes

#### Definindo uma constante

In [5]:
# Definindo uma constante no TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [6]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [7]:
# Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor.eval()

ValueError: ignored

#### Acessando os valores de uma constante

In [8]:
session = tf.Session()

In [9]:
session.run(tf.global_variables_initializer())

In [10]:
tensor_value = session.run(tensor)

In [11]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variáveis

#### Definindo uma variável

In [12]:
# Definindo uma variável no TensorFlow
variable = tf.Variable([[30, 20], [10, 45]])

In [13]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [14]:
# Se uma sessão na for inicializada, não podemos acessar os valores das variáveis
variable.eval()

ValueError: ignored

#### Acessando os valores de uma variável

In [15]:
# Inicializando uma sessão
session = tf.Session()

In [16]:
# Inicializando TODAS as variáveis de uma seção
session.run(tf.global_variables_initializer())

In [17]:
# Executando o método eval no ambiente com a sessão inicializada para conseguir buscar os valores
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Instalando o TensorFlow 2.0

In [2]:
!pip install tensorflow-gpu==2.0.0

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.0.0'

### Constantes

#### Definindo uma constante

In [5]:
# Definindo uma constante no TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [6]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [7]:
# Acessando as dimensões de um tensor
tensor_20.shape

TensorShape([2, 2])

#### Acessando os valores de uma constante

In [8]:
# Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [9]:
# Podemos converter um numpy array para um tensor do TensorFlow
numpy_tensor = np.array([[23,  4], [32, 51]])

In [10]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variáveis

#### Definindo uma variável

In [12]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessando os valores de uma variável

In [13]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Alterando um valor específico de uma variável

In [14]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [15]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operações com tensores

In [16]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Adição entre um escalar e um tensor

In [17]:
tensor + 2

<tf.Tensor: id=22, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicação entre um escalar e um tensor

In [18]:
tensor * 5

<tf.Tensor: id=24, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Usando funções do numpy nos tensores do TensorFlow

In [19]:
# Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [20]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product (produto escalar) entre dois tensores

In [21]:
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [22]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [23]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings no TensorFlow 2.0

In [24]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=25, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operações simples com strings

In [25]:
tf.strings.length(tf_string)

<tf.Tensor: id=26, shape=(), dtype=int32, numpy=10>

In [26]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=30, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Armazenando arrays (vetores) de strings

In [27]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [28]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
